
" desable backwards compatibility with vi
set nocompatible

" enable filetype plugins and indent
filetype plugin indent on

" enable syntax highlighting
syntax enable

" This mapping comments a line in Python
map c I#<Space><ESC>=<CR>

" custom leader key
let mapleader = ","

set number
